
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi2.pascal.valitations.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int REAL = 60;
  public static final int BARRA = 5;
  public static final int PACKED = 46;
  public static final int TYPE = 54;
  public static final int CONST = 28;
  public static final int INTEGER_LIT = 76;
  public static final int STRING_LIT = 66;
  public static final int GRATER = 15;
  public static final int UNTIL = 55;
  public static final int LESS_EQUALS = 18;
  public static final int CORCHETE_R = 11;
  public static final int ACENT = 12;
  public static final int INTEGER = 59;
  public static final int CORCHETE_L = 10;
  public static final int BOOLEAN_LIT = 77;
  public static final int COND = 73;
  public static final int NOT = 43;
  public static final int LLAVE_R = 7;
  public static final int NIL = 42;
  public static final int ARRAY = 25;
  public static final int DIFFERENT = 14;
  public static final int VAR = 56;
  public static final int LLAVE_L = 6;
  public static final int THEN = 52;
  public static final int GOTO = 37;
  public static final int RECORD = 49;
  public static final int MOD = 41;
  public static final int COMA = 20;
  public static final int PLUS = 2;
  public static final int WHILE = 57;
  public static final int ASSIGNATION = 19;
  public static final int CHAR = 62;
  public static final int BOOLEAN = 61;
  public static final int LONGINT = 64;
  public static final int PARENTESIS_R = 9;
  public static final int DO = 30;
  public static final int FOR = 35;
  public static final int DIV = 29;
  public static final int DOWNTO = 31;
  public static final int RETURN = 69;
  public static final int PARENTESIS_L = 8;
  public static final int READLN = 68;
  public static final int ELSE = 32;
  public static final int BREAK = 70;
  public static final int DOT = 21;
  public static final int PROCEDURE = 47;
  public static final int EOF = 0;
  public static final int SEMICOLON = 22;
  public static final int REAL_LIT = 65;
  public static final int FUNCTION = 36;
  public static final int GRATER_EQUALS = 17;
  public static final int REPEAT = 50;
  public static final int LABEL = 40;
  public static final int MINUS = 3;
  public static final int IN = 39;
  public static final int OR = 45;
  public static final int SET = 51;
  public static final int error = 1;
  public static final int WRITELN = 67;
  public static final int CONTINUE = 71;
  public static final int IF = 38;
  public static final int ID = 74;
  public static final int OF = 44;
  public static final int END = 33;
  public static final int COLON = 23;
  public static final int FILE = 34;
  public static final int BEGIN = 26;
  public static final int CASE = 27;
  public static final int CHAR_LIT = 75;
  public static final int STRING = 63;
  public static final int LESS = 16;
  public static final int PROGRAM = 48;
  public static final int AND = 24;
  public static final int UMINUS = 72;
  public static final int TO = 53;
  public static final int WITH = 58;
  public static final int EQUALS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "BARRA",
  "LLAVE_L",
  "LLAVE_R",
  "PARENTESIS_L",
  "PARENTESIS_R",
  "CORCHETE_L",
  "CORCHETE_R",
  "ACENT",
  "EQUALS",
  "DIFFERENT",
  "GRATER",
  "LESS",
  "GRATER_EQUALS",
  "LESS_EQUALS",
  "ASSIGNATION",
  "COMA",
  "DOT",
  "SEMICOLON",
  "COLON",
  "AND",
  "ARRAY",
  "BEGIN",
  "CASE",
  "CONST",
  "DIV",
  "DO",
  "DOWNTO",
  "ELSE",
  "END",
  "FILE",
  "FOR",
  "FUNCTION",
  "GOTO",
  "IF",
  "IN",
  "LABEL",
  "MOD",
  "NIL",
  "NOT",
  "OF",
  "OR",
  "PACKED",
  "PROCEDURE",
  "PROGRAM",
  "RECORD",
  "REPEAT",
  "SET",
  "THEN",
  "TO",
  "TYPE",
  "UNTIL",
  "VAR",
  "WHILE",
  "WITH",
  "INTEGER",
  "REAL",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "LONGINT",
  "REAL_LIT",
  "STRING_LIT",
  "WRITELN",
  "READLN",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "UMINUS",
  "COND",
  "ID",
  "CHAR_LIT",
  "INTEGER_LIT",
  "BOOLEAN_LIT"
  };
}

